### PR TITLE
corr/masim-record: add hugetlbfs test

### PR DESCRIPTION
**Pull request by gautammenghani**
*Issue #, if available:*

*Description of changes:*
Add hugetlbfs test in masim-record, as discussed on mailing list - https://lore.kernel.org/damon/20220816205030.96988-1-sj@kernel.org/T/#t

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gautammenghani** [comment]
Hi,
Can you please explain how is min_wss and max_wss estimated? Currently I have just entered them by observing the values

**Comment by gautammenghani** [comment]
Hi @sjp38  please let me know if the hugepage test should be separate from the rest of the tests

**Comment by sj-aws** [comment]
I can't believe how I missed this so long.  Sincere apology for the delay, and appreciate your patience, Gautam!  I'm traveling now, so I might not be fully responsible.  I will get back as soon as possible.  Sorry for the late reply again!

**Comment by sj-aws** [comment]
> please let me know if the hugepage test should be separate from the rest of the tests

Just assuming it based on the access pattern we put in, and some of expected DAMON noise due to adaptive regions adjustment (it's a best-effort approach).

**Comment by sj-aws** [comment]
Anyway, the change looks good to me.  From next time, please make pull request against 'next' branch, not 'master' branch.

**Comment by sj-aws** [comment]
I wanted to merge this as is, but... Could you please add a 'Signed-off-by:' tag in the commit message?

**Comment by gautammenghani** [comment]
Thank you. Yes I've added the signed-off tag.

**Comment by sj-aws** [comment]
Thank you for your effort and patience, Gautham!

**Pull request merged**
